algo: SimplePolicyGradient
env: LunarLanderContinuous-v2
lr: 1e-2
hidden_sizes: [128, 128]
n_epochs: 100
batch_size: 5000
render: False
device: cuda:0
trained_model_path: ./cupboard/trained_models/simple_pg_landerv2_cont.pth
test: False
