algo: VanillaPolicyGradient
env: LunarLander-v2
lr: 1e-2
hidden_sizes: [32]
n_epochs: 200
batch_size: 5000
render: False
device: cuda:0
trained_model_path: ./cupboard/trained_models/vpg_lander.pth
test: True
